/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import dataBase.Estaciones;
import dataBase.Personals;
import dataBase.Unidades;
import dataBase.incendios;
import entidades.Personal;
import entidades.Unidad;
import entidades.llamadoIncendio;

import static java.awt.image.ImageObserver.ERROR;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EduardoHumberto
 */
public class consultaReportes extends javax.swing.JFrame {
   
editarRegistro eR= new editarRegistro();
    int numIn;
    llamadoIncendio tipoIn = new llamadoIncendio();
    Estaciones es = new Estaciones();
    incendios incens = new incendios();
    Personal per = new Personal();
    Personals ps = new Personals();
    Unidad Un = new Unidad();
    Unidades Uns = new Unidades();
    String nombreOp;
    int numU;
    int idOp;
    int idUn;
    String date;

    /**
     * Creates new form consultaReportes
     */
    public consultaReportes() {
        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableIncendios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        casos = new javax.swing.JTextField();
        mes = new com.toedter.calendar.JMonthChooser();
        year = new com.toedter.calendar.JYearChooser();
        buscar = new javax.swing.JButton();
        editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(204, 204, 255));

        tableIncendios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo Incenidio", "Fecha", "Dirección", "Teléfono Reportante", "Daños", "Herramientas", "Unidad", "Operador", "Descripción", "Tipo de Apoyo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableIncendios);

        jLabel1.setText("Casos Registrados :");

        casos.setEditable(false);

        buscar.setText("jButton1");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        editar.setText("e");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        escritorio.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(casos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(mes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(year, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(buscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(editar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addComponent(buscar)
                        .addGap(43, 43, 43)
                        .addComponent(editar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(buscar))
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(editar))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        numIn = 0;
        int d = mes.getMonth() + 1;

        date = String.valueOf(year.getYear()) + "-0" + String.valueOf(d);

        incens.setFecha(date);
        DefaultTableModel tablemodel = (DefaultTableModel) tableIncendios.getModel();
        tablemodel.setRowCount(0);
        numIn = 0;
        for (llamadoIncendio e : incens.obtenerFecha(ERROR)) {
//       

            tablemodel.addRow(new Object[]{e.getTipoIncendio(), e.getFechaIncendio(), e.getDireccionIncendio(), e.getReportanteIncendio(),
                e.getDanoIncendio(), e.getHerramientaIncendio(), e.getNumUnidad(), e.getNombreOperador(), e.getDescripcionIncendio(), e.getTipoApoyo()});
            numIn = numIn + 1;
        }

        if (numIn == 0) {
            JOptionPane.showMessageDialog(null, "No se encontraron registros");
            table();
        } else {
            tableIncendios.setModel(tablemodel);
            casos.setText(String.valueOf(numIn));

        }


    }//GEN-LAST:event_buscarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed


incens.setId(new incendios().obtener1(tableIncendios.getSelectedRow()));
escritorio.add(eR); 
        System.out.println(incens.getId());
eR.show();
        
    }//GEN-LAST:event_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaReportes().setVisible(true);
            }
        });
    }

    public void table() {
        DefaultTableModel tablemodel = (DefaultTableModel) tableIncendios.getModel();
        tablemodel.setRowCount(0);
        for (llamadoIncendio e : incens.obtenerTodos(ERROR)) {

            tablemodel.addRow(new Object[]{e.getTipoIncendio(), e.getFechaIncendio(), e.getDireccionIncendio(), e.getReportanteIncendio(),
                e.getDanoIncendio(), e.getHerramientaIncendio(), e.getNumUnidad(), e.getNombreOperador(), e.getDescripcionIncendio(), e.getTipoApoyo()});
            numIn = numIn + 1;
        }
        tableIncendios.setModel(tablemodel);
        casos.setText(String.valueOf(numIn));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField casos;
    private javax.swing.JButton editar;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JMonthChooser mes;
    private javax.swing.JTable tableIncendios;
    private com.toedter.calendar.JYearChooser year;
    // End of variables declaration//GEN-END:variables
}
