/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import dataBase.Personals;
import dataBase.Unidades;
import dataBase.incendios;
import entidades.Personal;
import entidades.Unidad;
import entidades.llamadoIncendio;
import static java.awt.image.ImageObserver.ERROR;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author EduardoHumberto
 */
public class editarRegistro extends javax.swing.JInternalFrame {
     static int tipoI;
    static int apoyo;
    public int personal;
    
//Calendar fecha = Calendar.getInstance();    
    
    llamadoIncendio tipo= new llamadoIncendio();
    Calendar fecha = new GregorianCalendar();
Personals per = new Personals();
Unidades Un = new Unidades ();
Unidad U = new Unidad();
incendios in=new incendios();



    /**
     * Creates new form editarRegistro
     */
    public editarRegistro() {
        initComponents();
        Date date = new Date();
        
//DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
//System.out.println("Fecha: "+dateFormat.format(date));
        
// conboB();
//  ComboU();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        btnIncendioC = new javax.swing.JButton();
        btnIncendioV = new javax.swing.JButton();
        btnIncendioN = new javax.swing.JButton();
        btnIncendioM = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtProp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtdirec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboUnidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBombero = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jComboApoyo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextDanos = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtHerramienta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnAceptar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        btnIncendioC.setText("Incendio casa");
        btnIncendioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioCActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(btnIncendioC);

        btnIncendioV.setText("Incedio vehículo");
        btnIncendioV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioVActionPerformed(evt);
            }
        });

        btnIncendioN.setText("Incendio negocio");
        btnIncendioN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioNActionPerformed(evt);
            }
        });

        btnIncendioM.setText("Incendio maleza");
        btnIncendioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioMActionPerformed(evt);
            }
        });

        jLabel2.setText("Propietario");

        jLabel1.setText("    Dirección:   ");

        jLabel4.setText("Unidad de servicio   ");

        jLabel5.setText("Operador");

        jLabel10.setText("Litros de agua");

        jLabel6.setText("Apoyo Recibido");

        jComboApoyo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambulancia", "Policía Municipal", "Policía Federal" }));

        jLabel3.setText("Descripción de   daños :");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextDanos.setColumns(20);
        jTextDanos.setRows(5);
        jScrollPane2.setViewportView(jTextDanos);

        jLabel8.setText("Herramientas utilizadas");

        jLabel7.setText("Descripción del servicio :");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtDescripcion);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnIncendioV, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnIncendioN)
                        .addGap(32, 32, 32)
                        .addComponent(btnIncendioM, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProp)
                            .addComponent(txtdirec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBombero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboApoyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtHerramienta)
                            .addComponent(jScrollPane3))
                        .addGap(147, 147, 147))))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIncendioV)
                        .addComponent(btnIncendioN)
                        .addComponent(btnIncendioM))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBombero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jComboApoyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncendioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioCActionPerformed
        tipoI= 1;

        JOptionPane.showMessageDialog(null,"Incendio casa/habitación");
    }//GEN-LAST:event_btnIncendioCActionPerformed

    private void btnIncendioVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioVActionPerformed
        tipoI= 2;

        JOptionPane.showMessageDialog(null,"Incendio de vehículo");
    }//GEN-LAST:event_btnIncendioVActionPerformed

    private void btnIncendioNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioNActionPerformed
        tipoI= 3;

        JOptionPane.showMessageDialog(null,"Incendio de negocio");
    }//GEN-LAST:event_btnIncendioNActionPerformed

    private void btnIncendioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioMActionPerformed
        tipoI= 4;

        JOptionPane.showMessageDialog(null,"Incendio de maleza");
    }//GEN-LAST:event_btnIncendioMActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        apoyo= jComboApoyo.getSelectedIndex()+1;
        //        int dia = fecha.get(Calendar.DATE);
        //        Calendar.
        //        int mes= fecha.get(Calendar.MONTH);
        //        int año = Calendar.YEAR;


       
        
        new incendios().modificar(Integer.toString(tipoI),txtdirec.getText(),txtProp.getText(), jTextDanos.getText(),
                (int) jComboUnidad.getSelectedItem(), jComboBombero.getSelectedItem().toString(), txtDescripcion.getText(), 
                Integer.toString(apoyo));
//        
        
    }//GEN-LAST:event_btnAceptarActionPerformed
  public void conboB (){
         DefaultComboBoxModel comboModel = (DefaultComboBoxModel) jComboBombero.getModel();
      for (Personal e: per.obtenerTodos(ERROR)){
     comboModel.addElement(e.getApellidoPersonal()+" "+e.getNombrePersonal());
                     
       }
        jComboBombero.setModel(comboModel);
    }
    
    public void ComboU(){
        DefaultComboBoxModel comboModel2 = (DefaultComboBoxModel) jComboUnidad.getModel();
      for (Unidad e: Un.obtenerTodos(ERROR)){
     comboModel2.addElement((e.getNumeroUnidad()));
                     comboModel2.getElementAt(e.getId());
       }
        jComboUnidad.setModel(comboModel2);
    }
public void datos(){
//  

int ti=0;
String tipo=in.enviar1().getTipoIncendio();
//ENUM('CASA', 'VEHICULO', 'NEGOCIO', 'MALEZA')

 if (tipo.equals("CASA")) {
            ti = 1;
        } else if (tipo.equals("VEHICULO")) {
            ti = 2;
        } else if (tipo.equals("NEGOCIO")) {
            ti = 3;
        }else if (tipo.equals("MALEZA")) {
            ti = 4;
        }
        
int i=0;
String Tapoyo=in.enviar1().getTipoApoyo();
 if (Tapoyo.equals("Ambulancia")) {
            i = 0;
        } else if (Tapoyo.equals("Policía Municipal")) {
            i = 1;
        } else if (Tapoyo.equals("Policía Federal")) {
            i = 2;
        }
 tipoI=ti;
    System.out.println(tipoI);
txtProp.setText(in.enviar1().getPropietario());
txtdirec.setText(in.enviar1().getDireccionIncendio());
jComboUnidad.setSelectedItem(in.enviar1().getNumUnidad());
jComboBombero.setSelectedItem(in.enviar1().getNombreOperador());
jComboApoyo.setSelectedIndex(i);
jTextDanos.setText(in.enviar1().getDanoIncendio());
txtHerramienta.setText(in.enviar1().getHerramientaIncendio());
txtDescripcion.setText(in.enviar1().getDescripcionIncendio());

    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnIncendioC;
    private javax.swing.JButton btnIncendioM;
    private javax.swing.JButton btnIncendioN;
    private javax.swing.JButton btnIncendioV;
    private javax.swing.JComboBox<String> jComboApoyo;
    private javax.swing.JComboBox<String> jComboBombero;
    private javax.swing.JComboBox<String> jComboUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextDanos;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtHerramienta;
    private javax.swing.JTextField txtProp;
    private javax.swing.JTextField txtdirec;
    // End of variables declaration//GEN-END:variables
}
