/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import dataBase.Personals;
import dataBase.Unidades;
import dataBase.incendios;
import entidades.Personal;
import entidades.Unidad;
import entidades.llamadoIncendio;
import static java.awt.image.ImageObserver.ERROR;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author EduardoHumberto
 */
public class editarRegistro extends javax.swing.JInternalFrame {
     static int tipoI;
    static int apoyo;
    public int personal;
//Calendar fecha = Calendar.getInstance();    
    
    llamadoIncendio tipo= new llamadoIncendio();
    Calendar fecha = new GregorianCalendar();
Personals per = new Personals();
Unidades Un = new Unidades ();
Unidad U = new Unidad();



    /**
     * Creates new form editarRegistro
     */
    public editarRegistro() {
        initComponents();
        Date date = new Date();
        
DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
System.out.println("Fecha: "+dateFormat.format(date));

 conboB();
  ComboU();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        btnIncendioC = new javax.swing.JButton();
        btnIncendioV = new javax.swing.JButton();
        btnIncendioN = new javax.swing.JButton();
        btnIncendioM = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTexUbic = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextDanos = new javax.swing.JTextArea();
        txtTel = new javax.swing.JTextField();
        jComboUnidad = new javax.swing.JComboBox<>();
        jComboBombero = new javax.swing.JComboBox<>();
        jComboApoyo = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtHerramienta = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();

        setClosable(true);

        btnIncendioC.setText("Incendio casa");
        btnIncendioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioCActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(btnIncendioC);

        btnIncendioV.setText("Incedio vehículo");
        btnIncendioV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioVActionPerformed(evt);
            }
        });

        btnIncendioN.setText("Incendio negocio");
        btnIncendioN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioNActionPerformed(evt);
            }
        });

        btnIncendioM.setText("Incendio maleza");
        btnIncendioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioMActionPerformed(evt);
            }
        });

        jTexUbic.setColumns(20);
        jTexUbic.setRows(5);
        jScrollPane2.setViewportView(jTexUbic);

        jTextDanos.setColumns(20);
        jTextDanos.setRows(5);
        jScrollPane3.setViewportView(jTextDanos);

        jComboApoyo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambulancia", "Policía Municipal", "Policía Federal" }));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane4.setViewportView(txtDescripcion);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnIncendioV, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIncendioN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIncendioM, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jComboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBombero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jComboApoyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIncendioV)
                        .addComponent(btnIncendioN)
                        .addComponent(btnIncendioM))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBombero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboApoyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncendioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioCActionPerformed
        tipoI= 1;

        JOptionPane.showMessageDialog(null,"Incendio casa/habitación");
    }//GEN-LAST:event_btnIncendioCActionPerformed

    private void btnIncendioVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioVActionPerformed
        tipoI= 2;

        JOptionPane.showMessageDialog(null,"Incendio de vehículo");
    }//GEN-LAST:event_btnIncendioVActionPerformed

    private void btnIncendioNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioNActionPerformed
        tipoI= 3;

        JOptionPane.showMessageDialog(null,"Incendio de negocio");
    }//GEN-LAST:event_btnIncendioNActionPerformed

    private void btnIncendioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioMActionPerformed
        tipoI= 4;

        JOptionPane.showMessageDialog(null,"Incendio de maleza");
    }//GEN-LAST:event_btnIncendioMActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        
    }//GEN-LAST:event_btnAceptarActionPerformed
  public void conboB (){
         DefaultComboBoxModel comboModel = (DefaultComboBoxModel) jComboBombero.getModel();
      for (Personal e: per.obtenerTodos(ERROR)){
     comboModel.addElement(e.getApellidoPersonal());
                     comboModel.getElementAt(e.getId());
       }
        jComboBombero.setModel(comboModel);
    }
    
    public void ComboU(){
        DefaultComboBoxModel comboModel2 = (DefaultComboBoxModel) jComboUnidad.getModel();
      for (Unidad e: Un.obtenerTodos(ERROR)){
     comboModel2.addElement((e.getNumeroUnidad()));
                     comboModel2.getElementAt(e.getId());
       }
        jComboUnidad.setModel(comboModel2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnIncendioC;
    private javax.swing.JButton btnIncendioM;
    private javax.swing.JButton btnIncendioN;
    private javax.swing.JButton btnIncendioV;
    private javax.swing.JComboBox<String> jComboApoyo;
    private javax.swing.JComboBox<String> jComboBombero;
    private javax.swing.JComboBox<String> jComboUnidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTexUbic;
    private javax.swing.JTextArea jTextDanos;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtHerramienta;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
