/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import dataBase.Estaciones;
import dataBase.Unidades;
import entidades.Estacion;
import entidades.Unidad;
import static java.awt.image.ImageObserver.ERROR;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author EduardoHumberto
 */
public class vistaUnidades extends javax.swing.JInternalFrame {
 Estaciones es = new Estaciones();
 Unidades uns= new Unidades();
Unidad e = new Unidad();
    /**
     * Creates new form vistaUnidades
     */
    public vistaUnidades() {
        initComponents();
        table();
        combo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        esc = new javax.swing.JDesktopPane();
        btnAu = new javax.swing.JButton();
        numUnidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jComboE = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblU = new javax.swing.JTable();
        edit = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();

        esc.setBackground(new java.awt.Color(255, 255, 255));

        btnAu.setText("Agregar Unidad");
        btnAu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de Unidad: ");

        jLabel2.setText("Descripción");

        jComboE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));

        jLabel3.setText("Estación ");

        tblU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm. Unidad", "Descripción", "Estación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblU);

        edit.setText("Editar");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        esc.setLayer(btnAu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(numUnidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(txtDesc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jComboE, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(edit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(eliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escLayout = new javax.swing.GroupLayout(esc);
        esc.setLayout(escLayout);
        escLayout.setHorizontalGroup(
            escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAu)
                    .addGroup(escLayout.createSequentialGroup()
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(eliminar)
                                .addComponent(jComboE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(escLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(edit)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escLayout.setVerticalGroup(
            escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(btnAu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit)
                    .addComponent(eliminar))
                .addGap(58, 58, 58))
            .addGroup(escLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(esc)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(esc)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuActionPerformed


        if(txtDesc.getText().length()==0 ){
            
    JOptionPane.showMessageDialog(null,"Por favor llena todos los campos");
}else if(jComboE.getSelectedIndex()==0){
  JOptionPane.showMessageDialog(null,"Por favor selecciona una estación");
}else{
    try{    

        e.setNumeroUnidad(Integer.parseInt(numUnidad.getText()));
        e.setDescripcion(txtDesc.getText());
        e.setEstacion(jComboE.getSelectedItem().toString());

        
        uns.guardar(e);
         table();
}catch(NumberFormatException msj){
            JOptionPane.showMessageDialog(null,"Error al guardar algún tipo de dato");
        }
                
    }//GEN-LAST:event_btnAuActionPerformed
    }
    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
new Unidades().modificar(tblU.getSelectedRow(),Integer.parseInt(numUnidad.getText()), txtDesc.getText(), jComboE.getSelectedItem().toString());
table();
    }//GEN-LAST:event_editActionPerformed

    private void tblUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUMouseClicked
numUnidad.setText(String.valueOf(tblU.getValueAt(tblU.getSelectedRow(),0)));
txtDesc.setText(String.valueOf(tblU.getValueAt(tblU.getSelectedRow(),1)));
jComboE.setSelectedIndex(0);

    }//GEN-LAST:event_tblUMouseClicked

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
int c=JOptionPane.showConfirmDialog(null,"¿Eliminar unidad?");
if(c==0)      {
    new Unidades().eliminar1(tblU.getSelectedRow());
}

table();
    }//GEN-LAST:event_eliminarActionPerformed
public void combo(){
    DefaultComboBoxModel comboModel = (DefaultComboBoxModel) jComboE.getModel();

        for (Estacion e : es.obtenerTodos(ERROR)) {
            comboModel.addElement(e.getNombreEstacion());

        }
        jComboE.setModel(comboModel);
}

public void table() {

        DefaultTableModel tablemodel = (DefaultTableModel) tblU.getModel();
        tablemodel.setRowCount(0);

        for (Unidad e : uns.obtenerTodos(ERROR)) {
           
           tablemodel.addRow(new Object[]{e.getNumeroUnidad(),e.getDescripcion(),e.getEstacion()});

        }
        tblU.setModel(tablemodel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAu;
    private javax.swing.JButton edit;
    private javax.swing.JButton eliminar;
    private javax.swing.JDesktopPane esc;
    private javax.swing.JComboBox<String> jComboE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numUnidad;
    private javax.swing.JTable tblU;
    private javax.swing.JTextField txtDesc;
    // End of variables declaration//GEN-END:variables
}
