/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import dataBase.Personals;
import dataBase.Unidades;
import dataBase.incendios;
import entidades.Personal;
import entidades.Unidad;
import entidades.llamadoIncendio;
import static java.awt.image.ImageObserver.ERROR;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author EduardoHumberto
 */
public class vistaCrearReporte extends javax.swing.JInternalFrame {
 static int tipoI;
    static int apoyo;
    public int personal;
//Calendar fecha = Calendar.getInstance();    
    
    llamadoIncendio tipo= new llamadoIncendio();
    Calendar fecha = new GregorianCalendar();
Personals per = new Personals();
Unidades Un = new Unidades ();
Unidad U = new Unidad();
incendios in=new incendios();
    /**
     * Creates new form vistaCrearReporte
     */
    public vistaCrearReporte() {
        initComponents();
        Date date = new Date();
        
DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
System.out.println("Fecha: "+dateFormat.format(date));

 conboB();
  ComboU();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        esc = new javax.swing.JDesktopPane();
        btnIncendioC = new javax.swing.JButton();
        btnIncendioV = new javax.swing.JButton();
        btnIncendioN = new javax.swing.JButton();
        btnIncendioM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTexUbic = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextDanos = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jComboUnidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBombero = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboApoyo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtHerramienta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setClosable(true);

        esc.setBackground(new java.awt.Color(204, 204, 255));

        btnIncendioC.setText("Incendio casa");
        btnIncendioC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioCActionPerformed(evt);
            }
        });

        btnIncendioV.setText("Incedio vehículo");
        btnIncendioV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioVActionPerformed(evt);
            }
        });

        btnIncendioN.setText("Incendio negocio");
        btnIncendioN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioNActionPerformed(evt);
            }
        });

        btnIncendioM.setText("Incendio maleza");
        btnIncendioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncendioMActionPerformed(evt);
            }
        });

        jLabel1.setText("    Dirección:   ");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTexUbic.setColumns(20);
        jTexUbic.setRows(5);
        jScrollPane1.setViewportView(jTexUbic);

        jLabel2.setText("Teléfono del reportante :");

        jLabel3.setText("Descripción de   daños :");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextDanos.setColumns(20);
        jTextDanos.setRows(5);
        jScrollPane2.setViewportView(jTextDanos);

        jLabel4.setText("Unidad de servicio   ");

        jLabel5.setText("Operador");

        jLabel6.setText("Apoyo Recibido");

        jComboApoyo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambulancia", "Policía Municipal", "Policía Federal" }));

        jLabel7.setText("Descripción del servicio :");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtDescripcion);

        jLabel8.setText("Herramientas utilizadas");

        jLabel9.setText("Propietario ");

        jLabel10.setText("Litros de agua");

        jLabel11.setText("Hidrante ");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        esc.setLayer(btnIncendioC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(btnIncendioV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(btnIncendioN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(btnIncendioM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(txtTel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jComboUnidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jComboBombero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jComboApoyo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(txtHerramienta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jSpinner1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jSpinner2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        esc.setLayer(btnAceptar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escLayout = new javax.swing.GroupLayout(esc);
        esc.setLayout(escLayout);
        escLayout.setHorizontalGroup(
            escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBombero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLabel6))
                    .addGroup(escLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escLayout.createSequentialGroup()
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel11))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(escLayout.createSequentialGroup()
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHerramienta)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addGroup(escLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboApoyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(escLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escLayout.createSequentialGroup()
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escLayout.createSequentialGroup()
                                .addComponent(btnIncendioC)
                                .addGap(35, 35, 35)
                                .addComponent(btnIncendioV, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(escLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextField1)
                                .addGap(57, 57, 57)))
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(escLayout.createSequentialGroup()
                                .addComponent(btnIncendioN, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnIncendioM, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(escLayout.createSequentialGroup()
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(escLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        escLayout.setVerticalGroup(
            escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncendioC)
                    .addComponent(btnIncendioV)
                    .addComponent(btnIncendioN)
                    .addComponent(btnIncendioM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAceptar)))
                    .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(14, 14, 14)
                .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(escLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(escLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBombero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jComboApoyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(esc)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(esc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncendioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioMActionPerformed
        tipoI= 4;

        JOptionPane.showMessageDialog(null,"Incendio de maleza");
    }//GEN-LAST:event_btnIncendioMActionPerformed

    private void btnIncendioNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioNActionPerformed
        tipoI= 3;

        JOptionPane.showMessageDialog(null,"Incendio de negocio");
    }//GEN-LAST:event_btnIncendioNActionPerformed

    private void btnIncendioVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioVActionPerformed
        tipoI= 2;

        JOptionPane.showMessageDialog(null,"Incendio de vehículo");
    }//GEN-LAST:event_btnIncendioVActionPerformed

    private void btnIncendioCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncendioCActionPerformed
        tipoI= 1;

        JOptionPane.showMessageDialog(null,"Incendio casa/habitación");
    }//GEN-LAST:event_btnIncendioCActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        apoyo= jComboApoyo.getSelectedIndex()+1;
        //        int dia = fecha.get(Calendar.DATE);
        //        Calendar.
        //        int mes= fecha.get(Calendar.MONTH);
        //        int año = Calendar.YEAR;

        Date date = new Date();

        
        tipo.setTipoIncendio(Integer.toString(tipoI));
        tipo.setFechaIncendio(date);
        tipo.setDireccionIncendio(jTexUbic.getText());
        tipo.setReportanteIncendio(txtTel.getText());
        tipo.setDanoIncendio(jTextDanos.getText());
        tipo.setHerramientaIncendio(txtHerramienta.getText());
        tipo.setNumUnidad((int) jComboUnidad.getSelectedItem());
        System.out.println(jComboUnidad.getSelectedItem());
        tipo.setNombreOperador(jComboBombero.getSelectedItem().toString());

        tipo.setDescripcionIncendio(txtDescripcion.getText());
        tipo.setTipoApoyo(Integer.toString(apoyo));

        in.guardar(tipo);
    }//GEN-LAST:event_btnAceptarActionPerformed
public void conboB (){
         DefaultComboBoxModel comboModel = (DefaultComboBoxModel) jComboBombero.getModel();
      for (Personal e: per.obtenerTodos(ERROR)){
     comboModel.addElement(e.getApellidoPersonal()+" "+e.getNombrePersonal());
                     
       }
        jComboBombero.setModel(comboModel);
    }
    
    public void ComboU(){
        DefaultComboBoxModel comboModel2 = (DefaultComboBoxModel) jComboUnidad.getModel();
      for (Unidad e: Un.obtenerTodos(ERROR)){
     comboModel2.addElement((e.getNumeroUnidad()));
                     
       }
        jComboUnidad.setModel(comboModel2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnIncendioC;
    private javax.swing.JButton btnIncendioM;
    private javax.swing.JButton btnIncendioN;
    private javax.swing.JButton btnIncendioV;
    private javax.swing.JDesktopPane esc;
    private javax.swing.JComboBox<String> jComboApoyo;
    private javax.swing.JComboBox<String> jComboBombero;
    private javax.swing.JComboBox<String> jComboUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTexUbic;
    private javax.swing.JTextArea jTextDanos;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtHerramienta;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
